[package]
name = "supershorty"
version = "0.3.0"
authors = ["チセ <123655015+chise0713@users.noreply.github.com>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
description = "A BSD-styled CLI parser"
repository = "https://github.com/chise0713/supershorty"
keywords = ["argument", "cli", "arg", "parser", "parse"]
categories = ["command-line-interface"]

[lib]
proc-macro = true

[dependencies]
darling = "^0.20"
proc-macro2 = "^1"
quote = "^1"
syn = { version = "^2", features = ["full"] }
